---
- name: Install and Configure Jenkins
  hosts: jenkins
  become: yes
  
  tasks:
    - name: Remove old Jenkins repository files
      shell: |
        rm -f /etc/apt/sources.list.d/jenkins.list*
        rm -f /usr/share/keyrings/jenkins-keyring.asc
      ignore_errors: yes

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Java 17
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Download Jenkins GPG key
      shell: |
        curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null

    - name: Add Jenkins repository
      shell: |
        echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/" | tee /etc/apt/sources.list.d/jenkins.list > /dev/null
      
    - name: Update apt after adding repo
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: yes

    - name: Wait for Jenkins to start
      wait_for:
        port: 8080
        delay: 10
        timeout: 300

    - name: Get Jenkins initial admin password
      slurp:
        src: /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_initial_password

    - name: Display Jenkins initial password
      debug:
        msg: "Jenkins Initial Password: {{ jenkins_initial_password.content | b64decode }}"
